version: '3.9'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      API_KEY: ${API_KEY}
    restart: always

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    restart: always
