version: '3.9'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    restart: always
