name: CI/CD Workflow with Docker

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Container
        run: docker build -t backend-container ./server

      - name: Run Backend Container
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          docker run -d --name backend-container -p 5000:5000 \
            --env DB_PASSWORD=${DB_PASSWORD} \
            --env API_KEY=${API_KEY} \
            backend-container

      - name: Wait for Backend to Initialize
        run: sleep 10

      - name: Test Backend Health Endpoint
        run: |
          curl -f http://localhost:5000/health || (echo "Backend tests failed" && exit 1)

      - name: Stop Backend Container
        run: |
          docker stop backend-container
          docker rm backend-container

  frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend Container
        run: docker build -t frontend-container ./client

      - name: Run Frontend Container for Testing
        run: |
          docker run -d --name frontend-container -p 3000:80 frontend-container
          sleep 10
          curl -f http://localhost:3000 || (echo "Frontend tests failed" && exit 1)

      - name: Stop Frontend Container
        run: |
          docker stop frontend-container
          docker rm frontend-container

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/build
