name: CI/CD Workflow with Existing GHCR Images

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Test Backend with GHCR Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Backend Image from GHCR
        run: docker pull ghcr.io/${{ github.repository_owner }}/itconsultantservice-backend:latest

      - name: Run Backend Container for Testing
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          docker run -d --name backend-container -p 5000:5000 \
            --env DB_PASSWORD=${DB_PASSWORD} \
            --env API_KEY=${API_KEY} \
            ghcr.io/${{ github.repository_owner }}/itconsultantservice-backend:latest

      - name: Wait for Backend to Initialize
        run: sleep 10

      - name: Test Backend Health Endpoint
        run: |
          curl -f http://localhost:5000/health || (echo "Backend tests failed" && exit 1)

      - name: Stop Backend Container
        run: |
          docker stop backend-container
          docker rm backend-container

  frontend:
    name: Deploy Frontend from Code to GitHub Pages
    runs-on: ubuntu-latest
    needs: backend # Optional: Keep if frontend deployment depends on backend tests passing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install

      - name: Build Frontend
        working-directory: ./client
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/build
          publish_branch: gh-pages
          # Optional: CNAME settings if you have a custom domain
          # cname: yourdomain.com