name: Monorepo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Install dependencies for the backend
      - name: Install backend dependencies
        run: |
          cd server
          npm install

      # Step 4: Run backend tests
      - name: Run backend tests
        run: |
          cd server
          npm test

      # Step 5: Run linting for the backend
      - name: Run backend lint
        run: |
          cd server
          npm run lint

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    needs: backend # Runs only if the backend job succeeds

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Install dependencies for the frontend
      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      # Step 4: Build the frontend
      - name: Build frontend
        run: |
          cd client
          npm run build

      # Step 5: Run frontend tests
      - name: Run frontend tests
        run: |
          cd client
          npm test

      # Step 6: Run linting for the frontend
      - name: Run frontend lint
        run: |
          cd client
          npm run lint
